# This is a configuration file for the config package written
# by RStudio. To use, make sure the package `config` is installed,
# via console:
#
# R > install.packages("config")
#
# Then, you can load within a notebook chunk with `library(config)`.
#
# To use default config settings, simply write `config::get()`.
#
# You can learn more at:
#   https://cran.r-project.org/web/packages/config/vignettes/introduction.html.
default:
  path:
    root: !expr rprojroot::find_rstudio_root_file()
    data: !expr file.path(rprojroot::find_rstudio_root_file(), "data")
    raw_data: !expr file.path(rprojroot::find_rstudio_root_file(), "data", "raw")
    derived_data: !expr file.path(rprojroot::find_rstudio_root_file(), "data", "derived")
    metadata: !expr file.path(rprojroot::find_rstudio_root_file(), "data", "metadata")
    figures: !expr file.path(rprojroot::find_rstudio_root_file(), "reports", "figures")
    reports: !expr file.path(rprojroot::find_rstudio_root_file(), "reports", "reports")
    resources: !expr file.path(rprojroot::find_rstudio_root_file(), "resources")
    source: !expr file.path(rprojroot::find_rstudio_root_file(), "R")

  # Defining layers to extract
  layer_names: !expr c(
      "Greenup", "MidGreenup", "Peak", "Maturity",
      "Senescence", "MidGreendown", "Dormancy", "EVI_Minimum",
      "EVI_Amplitude", "EVI_Area")

  datum: "epsg:4326"
    


