
default:
  path:
    root: !expr rprojroot::find_rstudio_root_file()
    data: !expr file.path(rprojroot::find_rstudio_root_file(), "data")
    raw_data: !expr file.path(rprojroot::find_rstudio_root_file(), "data", "raw")
    derived_data: !expr file.path(rprojroot::find_rstudio_root_file(), "data", "derived")
    metadata: !expr file.path(rprojroot::find_rstudio_root_file(), "data", "metadata")
    figures: !expr file.path(rprojroot::find_rstudio_root_file(), "reports", "figures")
    reports: !expr file.path(rprojroot::find_rstudio_root_file(), "reports", "reports")
    resources: !expr file.path(rprojroot::find_rstudio_root_file(), "resources")
    source: !expr file.path(rprojroot::find_rstudio_root_file(), "R")

  layer_names: !expr c(
      "Greenup", "MidGreenup", "Peak", "Maturity",
      "Senescence", "MidGreendown", "Dormancy", "EVI_Minimum",
      "EVI_Amplitude", "EVI_Area")

  datum: "epsg:4326"

  ncores: !expr future::availableCores()
  futureplan: !expr future::plan("multisession", workers = future::availableCores())
  progress_aes: !expr progressr::handlers("cli")
  scinot: !expr options(scipen = 999)

    


